General Detection Base on Maivin
DeepViewML/detectimg pull request #1
Opened 2023-07-19 16:38 UTC by matt-auzone

2023-07-19 17:37 UTC, sebastient requested changes
Overall this is working towards the goal of having stand-alone, well-documented samples on our GitHub and most of the requested changes are related to cleaning the project files.  

I would like to see more effort put into the documentation, both in the README having a Quick Start section with screenshots showing what a user should expect to see as well as the detectimg.c inline documentation expanded.  The README examples should show the expected text output from detectimg.c and explain how the box coordinates can be de-normalized by hand to "draw" (manually, the demo doesn't output images) the bounding box over the objects and confirm it is working as expected.  I would also suggest either a different image or the full coco trained ModelPack as this example I'm not sure if the bus and people are both detected?  Please confirm (@ovesgarciareinier might have suggestions as well here).

As far as the detectimg.c inline documentation, refer to labelimg.c in the deepview-rt source code as an example of what's expected, it goes into details of what's being done and why.  Currently in this repository the comments are pretty light, for example this here.

`// Load model from file
err = vaal_load_model_file(ctx, model);`

The comment doesn't add anything because the function name is already descriptive.  What should be noted is that this function loads from file using a filename and pointing out alternative options from vaal.h to load from memory, as an example.

2023-07-19 17:37 UTC, sebastient commented on detect_app.c
This file should be called detectimg.c to match the project name.

2023-07-19 17:37 UTC, sebastient commented on vaal.h
This should not be included in this project, build using libvaal-dev from apt.

2023-07-19 17:37 UTC, sebastient commented on appconfig_0/face_detection_yunet_quant_512x384.rtm
This model is probably not needed since the demo is coco?

2023-07-19 17:37 UTC, sebastient commented on appconfig_0/Dockerfile
> +FROM deepview/linux-imx8:5.4.70
This should be updated to use the maivin/debian (bookworm or previous bullseye tags)  container that we're supporting now, the deepview/linux-imx8 is deprecated.

https://hub.docker.com/repository/docker/maivin/debian/general

2023-07-19 17:37 UTC, sebastient commented on appconfig_0/Dockerfile
> +FROM deepview/linux-imx8:5.4.70
Also most of the configuration below will no longer be required once you switch to maivin/debian as these are provided by the base Docker.  Refer to the GitHub repository for details.

https://github.com/MaivinAI/debian

2023-07-19 17:37 UTC, sebastient commented on appconfig_0/Dockerfile
> +ENV VAAL_LIBRARY=/usr/lib/aarch64-linux-gnu/libvaal.so
The VAAL_LIBRARY environment variable should not be required.

2023-07-19 17:37 UTC, sebastient commented on .devcontainer/Dockerfile
I don't think this file is meant to be in Git as the VSCode plugin should be generating it from the template file below.

2023-07-19 17:37 UTC, sebastient commented on .devcontainer/devcontainer.json
> +    "name": "torizon_detect_app",
Should just be detectimg for the name.

2023-07-19 17:37 UTC, sebastient commented on .vscode/launch.json
> +            "name": "C++ Launch",
Name should be more descriptive than the generic "C++ Launch" such as  "debug detectimg".

2023-07-19 17:37 UTC, sebastient commented on .vscode/settings.json
> +    "files.associations": {
I don't think these are needed in here as both are C++ aware C headers (extern "C" blocks when building from C++).

2023-07-19 17:37 UTC, sebastient commented on Makefile
Use detectimg instead of detect_app.

2023-07-19 17:37 UTC, sebastient commented on README.md
> +## EVK ArmV8
This section should be named NXP i.MX 8M Plus EVK

2023-07-19 17:37 UTC, sebastient commented on README.md
> +## Desktop x86-64
This section should be named Desktop Linux.  Technically either AMD64 or ARM64 will work with our APT repository and instructions should link to this Zendesk.

https://support.deepviewml.com/hc/en-us/articles/8328205801101

2023-07-19 17:37 UTC, sebastient commented on appconfig_0/config.yaml
Doesn't look like this should be in Git, assuming this is generated by the VSCode plugin?

2023-07-19 17:37 UTC, sebastient commented on appconfig_0/id_rsa
This shouldn't be in Git and also unclear why it is needed at all?  @saksham-auzone can you link to the Torizon VSCode Plugin documentation which covers the SSH configuration required for a project?

2023-07-19 17:37 UTC, sebastient commented on appconfig_0/id_rsa.pub
Same as the above comment for id_rsa.

2023-07-19 17:37 UTC, sebastient commented on appconfig_0/mpk-coco-people-320x320-relu-tensor-uint8-int8-e65.rtm
Shorten filename to just `modelpack-coco-people.rtm`.  Also make sure this is in Git LFS, not obvious from the PR if it is or not.

2023-07-19 17:37 UTC, sebastient commented on appconfig_0/test_image.png
Make sure this is in Git LFS as it isn't obvious in the PR if it is or not.

2023-07-27 05:36 UTC, sebastient requested changes
The README.md documentation is greatly improved.  Still some minor issues outstanding that should be addressed before merge.

2023-07-27 05:36 UTC, sebastient commented on .gitattributes
These should be global *.png *.rtm and so on in the root of the project, these types of git-lfs rules are universal.

2023-07-27 05:36 UTC, sebastient commented on .devcontainer/Dockerfile
This file shouldn't be here as it is presumably generated by Dockerfile.template.  If this is not the case then we need to address the fact that we have some hardcoded hashes in the file.

2023-08-11 16:13 UTC, matt-auzone commented on appconfig_0/test_image.png
Cannot use LFS with a forked repo

2023-08-11 17:31 UTC, sebastient requested changes
Overall the cleanup is looking good to merge now.  We need to move away from LFS to address GitHub PR limitations and hosting models in a separate project https://github.com/DeepViewML/peopledetect.

The README.md is greatly improved, future updates would be to cross-reference documentation from https://docs.deepviewml.com/vaal/1.4.2/index.html

The actual detectimg.c example still requires much better in-line documentation but this is not a gating issue and can be improved in the future.

2023-08-11 17:31 UTC, sebastient commented on .gitattributes
The *.rtm should be moved to .gitignore as we will not be bundling models into the project.  The *.png should be removed as LFS does not work well with GitHub PR and we'll only have a few images to be used as examples and which will not change often.

2023-08-11 17:31 UTC, sebastient commented on appconfig_0/mpk-coco-people.rtm
Should be removed.  Documentation will point to https://github.com/DeepViewML/peopledetect/releases/download/1.0/peopledetect.rtm or newer.

2023-08-11 17:31 UTC, sebastient commented on appconfig_0/test_image.png
Migrate from LFS to standard Git to avoid limitations with GitHub PR.

2023-08-14 17:56 UTC, sebastient approved these changes

2023-08-14 17:59 UTC, merged